#include "filter.h"


FilterTypeDef Filters;


/*Generated by:   http://www-users.cs.york.ac.uk/~fisher/mkfilter 
filtertype = Butterworth    passtype = Lowpass   ripple =   order = 3  
samplerate = 1000   corner1 = 50  corner2 = adzero = logmin =     */
#define GAINBtw50hz   (3.450423889e+02f)
void Butterworth50HzLPF(Bw50HzLPFTypeDef* pLPF)
{ 
	//¶þ½×²î·Ö£¿
      pLPF->xv[0] = pLPF->xv[1]; pLPF->xv[1] = pLPF->xv[2]; pLPF->xv[2] = pLPF->xv[3]; 
        pLPF->xv[3] = pLPF->input / GAINBtw50hz;
        pLPF->yv[0] = pLPF->yv[1]; pLPF->yv[1] = pLPF->yv[2]; pLPF->yv[2] = pLPF->yv[3]; 
        pLPF->yv[3] =   (pLPF->xv[0] + pLPF->xv[3]) + 3 * (pLPF->xv[1] + pLPF->xv[2])
                     + (  0.5320753683f * pLPF->yv[0]) + ( -1.9293556691f * pLPF->yv[1])
                     + (  2.3740947437f * pLPF->yv[2]);
        
	pLPF->output = pLPF->yv[3];
}


/* Digital filter designed by mkfilter/mkshape/gencode   A.J. Fisher
   Command line: /www/usr/fisher/helpers/mkfilter -Bu -Lp -o 2 -a 3.0000000000e-02 0.0000000000e+00 -l */
//#define NZEROS 2   #define NPOLES 2  static float xv[NZEROS+1], yv[NPOLES+1];
#define GAINBtw30Hz   1.278738361e+02f
void Butterworth30HzLPF(Bw30HzLPFTypeDef* pLPF)
{
	pLPF->xv[0] = pLPF->xv[1];
	pLPF->xv[1] = pLPF->xv[2]; 
  pLPF->xv[2] = pLPF->input / GAINBtw30Hz;
  pLPF->yv[0] = pLPF->yv[1];
	pLPF->yv[1] = pLPF->yv[2]; 
  pLPF->yv[2] = (pLPF->xv[0] + pLPF->xv[2]) + 2 * pLPF->xv[1]
                     + ( -0.7660066009f * pLPF->yv[0]) + (  1.7347257688f * pLPF->yv[1]);
  pLPF->output = pLPF->yv[2];
}


/////////////////////////////////////////////////
// Low pass filtering
void LPFUpdate(float height)
{	
	//Filters.AltitudeLPF_30.input = height;
	Filters.AltitudeLPF_50.input = height;

	//Butterworth30HzLPF(&Filters.AltitudeLPF_30);
	Butterworth50HzLPF(&Filters.AltitudeLPF_50);

}

float OneFactorialFilter(float height)
{
	float NewValue=height;
	static float Value=0;
	Value=OneFactorialFilter_Const*Value+(1-OneFactorialFilter_Const)*NewValue;
	return Value;
}
